# frozen_string_literal: true

require_relative "viz/version"
require_relative "viz/html"

require "stack_trace"
require "erb"
require "json"

module StackTrace
  module Viz
    LAYOUT_FILE = "../public/main.html.erb"

    class << self
      def save_current!(file_path = nil)
        HTML.new(StackTrace.current).save(file_path)
      end

      def as_json
        JSON.generate({
          file_path: "...",
          line_number: "",
          description: "Generated by StackTrace::Viz",
          trace: StackTrace.current
        })
      end
    end
  end
end
